#!/usr/bin/env node
/**
 * scripts/install-hooks.js
 * Registers the pre-push git hook for this repo.
 * Run once per developer machine: npm run hooks:install
 */

import { execSync } from "node:child_process";
import { writeFileSync, chmodSync } from "node:fs";
import { resolve, join } from "node:path";

const repoRoot = execSync("git rev-parse --show-toplevel", { encoding: "utf8" }).trim();
const hookPath = join(repoRoot, ".git", "hooks", "pre-push");
const scriptPath = resolve("scripts/pre-push.js");

const shim = `#!/bin/sh
# Auto-generated by scripts/install-hooks.js — do not edit manually.
exec node "${repoRoot}/watsonx-challenge-2026/scripts/pre-push.js"
`;

writeFileSync(hookPath, shim);
chmodSync(hookPath, 0o755);

console.log(`✔  pre-push hook installed → ${hookPath}`);
console.log(`   Points to: ${scriptPath}`);
